config/routes.rb
Rails.application.routes.draw do
  root to:'users#index'
  get 'reservations/new'
  resources :rooms do
    collection do
      get 'search', to:'rooms#search'
      get 'search', to:'rooms#freesearch'
    end
  end
  get 'rooms/new', to:'rooms#create'
  get 'users/show'=> "users#show"
  devise_for :users, controllers: { registrations: 'users/registrations' } 
  resources :reservations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :room,optional: true
    belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    has_many :reservations

    def self.search(search)
      if search
        Room.where(['adress LIKE ? OR introduction LIKE ? OR name LIKE ? OR price LIKE ?', "%#{search}%","%#{search}%","%#{search}%","%#{search}%"])
      else
        Room.all
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :profile, length: {maximum: 200}

  attr_accessor :current_password
  has_one_attached :image
  has_many :rooms
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery with: :exception

 # ログイン済ユーザーのみにアクセスを許可する
before_action :authenticate_user!, except:[:index]
  
 # deviseコントローラーにストロングパラメータを追加する          
 before_action :configure_permitted_parameters, if: :devise_controller?
  
 protected
 def configure_permitted_parameters
  # サインアップ時にnameのストロングパラメータを追加
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # アカウント編集の時にnameとprofileのストロングパラメータを追加
  devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile,:image])
 end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.where(user_id: current_user.id)
  end

  def new
   @room = Room.find(params[:id])
   @user_id = current_user.id
   @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    @totalprice = @reservation.room.price * @reservation.people * (@reservation.endday - @reservation.startday).to_i
    if @reservation.save
      flash[:notice] = "予約が完了しました"
      redirect_to reservation_path(@reservation.id)
    else
      render :new
    end
    
  end

	def show
    @reservation = Reservation.find(params[:id])
  end

  private
    def reservation_params
      params.require(:reservation).permit(:startday,:endday,:people,:totalday,:totalprice,:room_id).merge(user_id: current_user.id)
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(params.require(:room).permit(:name,:introduction,:price,:adress,:image))
    @room.user_id = current_user.id
    @room.save
    redirect_to rooms_path
  end

  def show
    @rooms = current_user.rooms
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  def search
    @rooms = Room.search(params[:search])
  end

  private
  def room_params
    params.require(:room).permit(:name,:introduction,:price,:adress,:image) 
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
  end
  
  def show
    @user = current_user
  end

  private
  def user_params
    params.require(:user).permit(:image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Potepanshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
    <a href="http://localhost:3000/"><img src= "https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png" alt="サイトロゴ画像"></a>
   </header>
  <%= yield %>
  <footer>
   <p>© 2020 POTEPAN.INC.</p>
  </footer>
  </body>
</html>

app/views/reservations/index.html.erb
<div id ="reservation_index">
<h2>予約履歴</h2>
<table>
<thead>
  <th>予約した部屋</th>
  <th>部屋名</th>
  <th>開始日</th>
  <th>終了日</th>
  <th>予約確定日時</th>
 </tr>
</thead>
 
<tbody>
 <tr>
 <% @reservations.each do |reservation| %> 
  <% @rooms = Room.where(id: reservation.room_id) %>
  <% @rooms.each do |room| %>
    <% if room.image.attached? %>
    <td><%= image_tag room.image, size: '100x100' %>
     <% else %>
      画像なし
     <% end %>
    </td>
  <td><%= reservation.room.name %></td>
  <td><%= reservation.startday %></td>
  <td><%= reservation.endday %></td>
  <td><%= reservation.created_at.to_s(:datetime_jp) %></td>
 </tr>
<% end %>
<% end %>
</tbody>
</table>

app/views/reservations/new.html.erb
<table id ="reservation_new_table">
<tr>
<% if @room.image.attached? %>
   <td><%= image_tag @room.image, size: '100x100' %>
    <% else %>
     画像なし
    <% end %>
   </td>
</tr>
<tr>
  <td><%= @room.name %></td>
</tr>
<tr>
  <td><%= @room.adress %></td>
</tr>
<tr>
  <td><%= @room.introduction %></td>
</tr>
<tr>
  <td>¥<%= @room.price %>/日</td>
</tr>
</table>

<div id="reservation_new">
 <h2>部屋を予約する</h2>
 <%= form_with model: @reservation do |f| %>    
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :room_id, value: @room.id %>
  <%= f.hidden_field :price, value: @room.price %>
    <table>
     <tr>
       <th><%= f.label :startday ,"開始日" %></th>
       <td><%= f.date_field :startday %></td>
     </tr>
 
     <tr>
       <th><%= f.label :endday ,"終了日" %></th>
       <td><%= f.date_field :endday %></td>
     </tr>
 
     <tr>
       <th><%= f.label :people ,"人数" %></th>
       <td><%= f.number_field :people %></td>
     </tr>
   </table>
   <div>
     <ul>
       <li><%= f.submit "予約する"%></li>
     </ul>
   </div>
 <% end %>

app/views/reservations/show.html.erb
<div id="reservation_confirm">

<% if flash[:notice] %>
<p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
  <th>開始</th>
    <td id><%= @reservation.startday %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @reservation.endday %></td>
  </tr>
  <tr>
    <th>宿泊日数</th>
    <td><%=  @totalday = (@reservation.endday - @reservation.startday).to_i %></td>
  </tr>
  <tr>
    <th>人数</th>
    <td><%= @reservation.people %></td>
  </tr>
  <tr>
  <th>料金</th>
  <td><%= @totalprice = @reservation.room.price * @reservation.people * (@reservation.endday - @reservation.startday).to_i %></td>
</tr>
</table>

app/views/rooms/index.html.erb
<div id ="room_index">
<h2>検索結果: <%= @rooms.count %>件</h2>
<table>
<thead>
 <tr>
  <th>画像</th>
  <th>名前</th>
  <th>住所</th>
  <th>ルーム紹介</th>
  <th>値段</th>
  <th>予約</th>
  <th>投稿者</th>
 </tr>
</thead>

<tbody>
 <tr>
 <% @rooms.each do |room| %>
  <% if room.image.attached? %>
  <td><%= image_tag room.image, size: '100x100' %></td>
  <% else %>
  <td>画像なし
  <% end %>
  </td>
  <td><%= room.name %></td>
  <td><%= room.adress %></td>
  <td><%= room.introduction %></td>
  <td><%= room.price %></td>
  <td><%= link_to "予約する", {controller: 'reservations', action: 'new', id: room.id} %></td>
  <td><%= room.user.name %></td>
 </tr>
<% end %>
</tbody>
</table>

app/views/rooms/new.html.erb
<div id="room_new">
 <h2>ルーム情報登録</h2>
  <%= form_with model: @room do |f| %>
   <table>
     <tr>
       <th><%= f.label :name ,"ルーム名" %></th>
       <td><%= f.text_field :name %></td>
     </tr>
 
     <tr>
       <th><%= f.label :introduction ,"ルーム紹介" %></th>
       <td><%= f.text_area :introduction %></td>
     </tr>
 
     <tr>
       <th><%= f.label :price ,"料金" %></th>
       <td><%= f.number_field :price %></td>
     </tr>
 
     <tr>
       <th><%= f.label :adress ,"住所" %></th>
       <td><%= f.text_field :adress %></td>
     </tr>

     <tr>
       <th><%= f.label :image ,"ルーム画像" %></th>
       <td><%= f.file_field :image %></td>
     </tr>     
     
   </table>
   <div>
     <ul>
       <li><%= f.submit "登録"%></li>
     </ul>
   </div>
 <% end %>

app/views/rooms/search.html.erb
<div id="search_room">
<h2>検索結果: <%= @rooms.count %>件</h2>
<table>
<thead>
 <tr>
  <th>画像</th>
  <th>名前</th>
  <th>住所</th>
  <th>ルーム紹介</th>
  <th>値段</th>
  <th>予約</th>
 </tr>
</thead>

<tbody>
 <tr>
 <% @rooms.each do |room| %>
  <% if room.image.attached? %>
  <td><%= image_tag room.image, size: '100x100' %></td>
  <% else %>
  <td>画像なし
  <% end %>
  </td>
  <td><%= room.name %></td>
  <td><%= room.adress %></td>
  <td><%= room.introduction %></td>
  <td><%= room.price %></td>
  <td><%= link_to "予約する", {controller: 'reservations', action: 'new', id: room.id} %></td>
 </tr>
 <% end %>
</tbody>
</table>
</div>

app/views/rooms/show.html.erb
<div id ="show_room">
<h2>登録済みルーム一覧</h2>
<table>
<thead>
 <tr>
  <th>画像</th>
  <th>名前</th>
  <th>住所</th>
  <th>値段</th>
  <th>詳細</th>
  <th>投稿者</th>
 </tr>
</thead>

<tbody>
  <tr>
  <% @rooms.each do |room| %>
   <% if room.image.attached? %>
   <td><%= image_tag room.image, size: '100x100' %>
    <% else %>
     画像なし
    <% end %>
   </td>
   <td><%= room.name %></td>
   <td><%= room.adress %></td>
   <td><%= room.price %></td>
   <td><%= link_to "予約する", {controller: 'reservations', action: 'new', id: room.id} %></td>
   <td><%= current_user.name %></td>
  </tr>
 <% end %>
</tbody>
</table>

app/views/users/index.html.erb
<img id="background_pic" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_cover_top.jpg" alt="背景画像">
 <h2 id="recomend_area" >おすすめのエリア</h2>

 <div id="image">
   <img id="tokyo" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_tokyo.jpg" alt="東京" width="292" height="243">
   <img id="osaka" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_osaka.jpg" alt="大阪" width="292" height="243">
   <img id="kyoto" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_kyoto.jpg" alt="京都" width="292" height="243">
   <img id="sapporo" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/img_sapporo.jpg" alt="札幌" width="292" height="243">
 </div>

   <h2 id="tokyo_text">東京</h2>
   <h2 id="osaka_text">大阪</h2>
   <h2 id="kyoto_text">京都</h2>
   <h2 id="sapporo_text">札幌</h2>

<% if user_signed_in? %>
 <div id="current_user_name">
  <%= current_user.name %>
 </div>

 <div id="current_user_image">
 <% if @user.image.attached? %>
 <%= image_tag @user.image, size: '50x50'%>
 <% end %>
 </div>
 
  <input type="checkbox" id="menu">
  <label class="menu" for="menu">メニュー</label>
   <div id="G">
    <%= link_to "ルーム登録", new_room_path %>
    <%= link_to "予約履歴" ,reservations_path %>
    <%= link_to "登録済みルーム一覧", room_path(:room_id) %>
    <%= link_to "設定", users_show_path %> 
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <%= link_to "すべてのルーム", rooms_path %> 
   </div>

   <div id="area_search">
    <h1>Potepan Shareでまだ体験したことのない旅をしよう</h1>
    <%= form_tag(search_rooms_path,:method => 'get') do %>
      <%= label_tag '都道府県で検索' %>
      <%= text_field_tag :search %>
      <%= submit_tag 'Search', :adress => nil %>
    <% end %>
   </div>

  <div id="area_search_header">
   <%= form_tag(search_rooms_path,:method => 'get') do %>
     <%= text_field_tag :search %>
     <%= submit_tag 'エリア検索', :adress => nil %>
   <% end %>
  </div>

  <div id="keyword_search_header">
   <%= form_tag(search_rooms_path,:method => 'get') do %>
     <%= text_field_tag :search %>
     <%= submit_tag 'キーワード検索' %>
   <% end %>
  </div>

<% else %>
<button id ="sign_in"><%= link_to "ログイン", new_user_session_path %></button>
<button id ="sign_up"><%= link_to "新規登録",  new_user_registration_path%></button>
<% end %>

app/views/users/show.html.erb
<div id="user_show">
 <h3>プロフィール画像:</h3>
 <div id="picture">
 <% if @user.image.attached? %>
 <%= image_tag @user.image, size: '100x100'%>
 </div> 
 <% else %>
    画像なし
 <% end %>
 <h3>ユーザー名</h3>
 <%= @user.name %>
 <h3>メールアドレス</h3>
 <%= @user.email %>
 <h3>パスワード</h3>
 <p>******</p>
 <h3>自己紹介</h3>
 <%= @user.profile%>
 <button id ="user_edit"><%= link_to "編集する", edit_user_registration_path %></button>
</div>